### PR TITLE
Added Hover Effect

### PR DESCRIPTION
**Pull request by Yash-271120**
Adding the hover effect was actually difficult. I used gsap for it.
refer [here](https://greensock.com/react/l) for gsap docs.

### CODE REVIEW

**Comment by jai-dewani** [comment]
There seems to be some build error, kindly check that and also make sure you add the new packages to package.json.

I don't know much about `gasp` so maybe you can answer this better, do we really need another library for doing hover text? 
I have seen simpler text hover using plain CSS, does this implementation provides any additional benefits?

**Comment by Yash-271120** [comment]
Hover effect using plain CSS can be done but on hover changes to css can be applied to that element only which we are hovering.
In our case that element was input. That's why as a way around I used gsap.

**Comment by jai-dewani** [comment]
Okay, go ahead and fix the build errors and don't forget to add the new dependency to package.json, or other's will have to install this new package separately even after doing `npm install`

**Comment by Yash-271120** [comment]
I think the build error is gone now!

**Comment by jai-dewani** [comment]
It's still there @Yash-271120 
Can you run the build process locally once before pushing just to check?

**Comment by Yash-271120** [comment]
Yes I build it locally it worked fine. I really can't find the problem here!

**Comment by jai-dewani** [comment]
Closing this PR because no activity in the last 4 months

**Pull request closed without merging**
